# AI Workforce Intelligence 2030

## Phase 2: Data Audit & Profiling

**Prepared By:** Akshat Karn

**Objective:**
To understand the dataset, assess its quality, identify potential issues, and prepare it for exploratory data analysis.

# Section-1
Importing all the libraries i.e pandas and numpy

In [8]:
import pandas as pd
import numpy as np

# Section-2

importing the datest to the colab enviroment from local space to here

In [9]:
df=pd.read_csv('/content/AI_Impact_on_Jobs_2030.csv')

# Section-3
This section consist of inital inspection that whether the data is loaded correctly or not

In [14]:
df.head(5)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing
2,AIJ-100002,HR Specialist,Education,Canada,High School,21,0.80,0.69,Yes,124800,"Kubernetes, Cloud Computing, TensorFlow, SQL, ...",Medium,-5,57,Startup,Low,3.14,No,3.54,Stable
3,AIJ-100003,Cybersecurity Analyst,Government,UK,Bachelor,5,0.29,0.94,No,199878,"Excel, Kubernetes, Prompt Engineering, Leadership",Medium,7,59,Enterprise,High,3.67,No,4.37,Declining
4,AIJ-100004,Healthcare Analyst,Education,UAE,PhD,20,0.11,0.92,No,178682,"SQL, Leadership, TensorFlow, Cybersecurity",Low,6,34,Startup,High,3.68,No,3.99,Stable

In [15]:
df.tail(5)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
2995,AIJ-102995,Data Scientist,Education,India,Bachelor,0,0.62,0.27,Hybrid,202565,"Azure, Project Management, Cloud Computing, Cy...",Medium,36,59,Enterprise,Moderate,4.54,Yes,1.27,Stable
2996,AIJ-102996,Data Engineer,Healthcare,UAE,PhD,4,0.52,0.57,Yes,37215,"Communication, PyTorch, Docker",Low,17,45,Startup,Low,2.71,No,2.56,Stable
2997,AIJ-102997,DevOps Engineer,Energy,Pakistan,High School,7,0.72,0.70,No,55179,"TensorFlow, Excel, Python, Docker",Medium,34,35,Startup,Low,4.88,Yes,3.17,Declining
2998,AIJ-102998,Data Scientist,Government,Australia,Bachelor,19,0.82,0.76,Hybrid,125291,"Cybersecurity, Cloud Computing, Deep Learning",Medium,21,47,Startup,Moderate,3.59,Yes,3.78,Stable
2999,AIJ-102999,HR Specialist,Retail,Germany,Master,9,0.68,0.44,No,152792,"Kubernetes, Cybersecurity, Communication",Low,32,44,Medium,Moderate,3.29,No,1.36,Growing

In [16]:
df.sample(5, random_state=42)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
1801,AIJ-101801,Machine Learning Engineer,Manufacturing,Canada,Master,6,0.71,0.95,Hybrid,31850,"PyTorch, Azure, Kubernetes",Medium,45,38,Startup,Moderate,3.33,Yes,1.68,Declining
1190,AIJ-101190,Robotics Engineer,Finance,USA,PhD,13,0.20,0.79,No,55123,"Leadership, Kubernetes, Python, Docker, Data V...",Low,-4,40,Startup,Moderate,2.96,Yes,1.08,Stable
1817,AIJ-101817,Financial Analyst,Education,USA,High School,14,0.74,0.65,No,60999,"Leadership, Prompt Engineering, AWS, Data Visu...",Low,6,41,Enterprise,Low,4.39,Yes,4.43,Stable
251,AIJ-100251,Cloud Architect,Technology,Germany,Bachelor,9,0.23,0.50,Yes,52495,"Cybersecurity, Azure, SQL, Docker, PyTorch, Cl...",Medium,34,55,Startup,Moderate,3.35,Yes,2.33,Growing
2505,AIJ-102505,Cloud Architect,Education,UAE,High School,11,0.87,0.47,Yes,151062,"Communication, Leadership, Kubernetes, Excel, ...",Medium,0,44,Enterprise,High,3.75,Yes,3.08,Stable

#Section-4
This section gives the very basic info about the dataset i.e no. coulumns rows name of columns and info regarding data types.

In [17]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 3000
Columns: 20

In [18]:
df.columns.tolist()

['Employee_ID',
 'Job_Title',
 'Industry',
 'Country',
 'Education_Level',
 'Years_Experience',
 'AI_Replacement_Risk',
 'Future_Demand_Score',
 'Remote_Work_Possibility',
 'Average_Salary_USD',
 'Required_Skills',
 'Automation_Level',
 'Job_Growth_2030',
 'Work_Hours_Per_Week',
 'Company_Size',
 'AI_Tool_Usage',
 'Performance_Score',
 'Upskilling_Needed',
 'Job_Satisfaction',
 'Hiring_Trend_2026']

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Employee_ID              3000 non-null   object
 1   Job_Title                3000 non-null   object
 2   Industry                 3000 non-null   object
 3   Country                  3000 non-null   object
 4   Education_Level          3000 non-null   object
 5   Years_Experience         3000 non-null   int64
 6   AI_Replacement_Risk      3000 non-null   float64
 7   Future_Demand_Score      3000 non-null   float64
 8   Remote_Work_Possibility  3000 non-null   object
 9   Average_Salary_USD       3000 non-null   int64
 10  Required_Skills          3000 non-null   object
 11  Automation_Level         3000 non-null   object
 12  Job_Growth_2030          3000 non-null   int64
 13  Work_Hours_Per_Week      3000 non-null   int64
 14  Company_Size             3000 non-null   object
 15  AI_Tool_Usage            3000 non-null   object
 16  Performance_Score        3000 non-null   float64
 17  Upskilling_Needed        3000 non-null   object
 18  Job_Satisfaction         3000 non-null   float64
 19  Hiring_Trend_2026        3000 non-null   object
dtypes: float64(4), int64(4), object(12)
memory usage: 468.9+ KB

# Section-5
This Section tells me about the unique values duplicate values and null values

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.isnull().sum()

Employee_ID                0
Job_Title                  0
Industry                   0
Country                    0
Education_Level            0
Years_Experience           0
AI_Replacement_Risk        0
Future_Demand_Score        0
Remote_Work_Possibility    0
Average_Salary_USD         0
Required_Skills            0
Automation_Level           0
Job_Growth_2030            0
Work_Hours_Per_Week        0
Company_Size               0
AI_Tool_Usage              0
Performance_Score          0
Upskilling_Needed          0
Job_Satisfaction           0
Hiring_Trend_2026          0
dtype: int64

In [24]:
df.nunique()

Employee_ID                3000
Job_Title                    20
Industry                     10
Country                      10
Education_Level               4
Years_Experience             26
AI_Replacement_Risk          91
Future_Demand_Score          80
Remote_Work_Possibility       3
Average_Salary_USD         2970
Required_Skills            2937
Automation_Level              3
Job_Growth_2030              56
Work_Hours_Per_Week          31
Company_Size                  3
AI_Tool_Usage                 3
Performance_Score           301
Upskilling_Needed             2
Job_Satisfaction            401
Hiring_Trend_2026             3
dtype: int64

#Section-6
This section Summarizes the data and provide the summary statistics of the Data.

In [20]:
df.describe()

,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Average_Salary_USD,Job_Growth_2030,Work_Hours_Per_Week,Performance_Score,Job_Satisfaction
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,12.383000,0.502910,0.601203,126641.746667,17.238333,44.773333,3.514643,3.026167
std,7.528958,0.261293,0.226674,55405.053057,16.230322,8.926469,0.873375,1.146361
min,0.000000,0.050000,0.200000,30221.000000,-10.000000,30.000000,2.000000,1.000000
25%,6.000000,0.280000,0.420000,77262.000000,3.000000,37.000000,2.760000,2.060000
50%,12.000000,0.500000,0.600000,127660.500000,17.000000,45.000000,3.540000,3.025000
75%,19.000000,0.730000,0.800000,174811.750000,31.000000,52.000000,4.270000,4.010000
max,25.000000,0.950000,0.990000,219998.000000,45.000000,60.000000,5.000000,5.000000

In [21]:
df.describe(include="object")

,Employee_ID,Job_Title,Industry,Country,Education_Level,Remote_Work_Possibility,Required_Skills,Automation_Level,Company_Size,AI_Tool_Usage,Upskilling_Needed,Hiring_Trend_2026
count,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
unique,3000,20,10,10,4,3,2937,3,3,3,2,3
top,AIJ-102999,Software Developer,Energy,UAE,Bachelor,Hybrid,"Cloud Computing, Kubernetes, Leadership",Low,Medium,Low,No,Growing
freq,1,164,335,347,782,1011,3,1037,1025,1033,1511,1010